<?php
require_once '../includes/db.php';
session_start();

if(!isset($_SESSION['user_id']) || $_SESSION['role'] !== 'admin'){
    header("Location: ../login.php");
    exit;
}

$report_type = isset($_GET['type']) ? $_GET['type'] : 'properties';
$date_from = isset($_GET['from']) ? $_GET['from'] : date('Y-m-01');
$date_to = isset($_GET['to']) ? $_GET['to'] : date('Y-m-d');

// Set filename
$filename = "transphil_report_{$report_type}_" . date('Y-m-d') . ".csv";

// Set headers for CSV download
header('Content-Type: text/csv; charset=utf-8');
header('Content-Disposition: attachment; filename="' . $filename . '"');

// Create output stream
$output = fopen('php://output', 'w');

// Add UTF-8 BOM for Excel compatibility
fprintf($output, chr(0xEF).chr(0xBB).chr(0xBF));

// ============================================
// COMPANY HEADER (appears on every report)
// ============================================
fputcsv($output, ['============================']);
fputcsv($output, ['TRANS-PHIL HOUSE CORPORATION']);
fputcsv($output, ['Real Estate Management System']);
fputcsv($output, ['============================']);
fputcsv($output, []);
fputcsv($output, ['Report Generated:', date('F d, Y h:i A')]);
fputcsv($output, ['Generated By:', $_SESSION['full_name']]);
fputcsv($output, ['Report Period:', date('M d, Y', strtotime($date_from)) . ' - ' . date('M d, Y', strtotime($date_to))]);
fputcsv($output, ['']);
fputcsv($output, ['Address: 1177 Bagtikan St, San Antonio Village, Makati City']);
fputcsv($output, ['Email: info@transphilhouse.com']);
fputcsv($output, ['']);
fputcsv($output, ['============================']);
fputcsv($output, []);

// ============================================
// SECTION 1: PROPERTIES REPORT
// ============================================
if($report_type == 'properties' || $report_type == 'full'){
    fputcsv($output, ['📊 PROPERTIES REPORT']);
    fputcsv($output, ['']);
    
    // Fetch data
    $stmt = $pdo->prepare("
        SELECT id, title, description, type, price, location, status, 
               is_featured, bedrooms, bathrooms, area, created_at 
        FROM properties 
        WHERE created_at BETWEEN ? AND ?
        ORDER BY created_at DESC
    ");
    $stmt->execute([$date_from, $date_to . ' 23:59:59']);
    $data = $stmt->fetchAll();
    
    // Column Headers
    fputcsv($output, ['#', 'Property Title', 'Type', 'Price (₱)', 'Location', 'Status', 'Featured', 'Beds', 'Baths', 'Area (sqm)', 'Date Listed']);
    
    // Data rows
    $counter = 1;
    $total_value = 0;
    foreach($data as $row){
        fputcsv($output, [
            $counter++,
            $row['title'],
            strtoupper($row['type']),
            number_format($row['price'], 2),
            $row['location'],
            strtoupper($row['status']),
            $row['is_featured'] ? 'YES' : 'NO',
            $row['bedrooms'] ?: '-',
            $row['bathrooms'] ?: '-',
            $row['area'] ?: '-',
            date('Y-m-d', strtotime($row['created_at']))
        ]);
        $total_value += $row['price'];
    }
    
    fputcsv($output, []);
    fputcsv($output, ['SUMMARY', '', '', '', '', '', '', '', '', '', '']);
    fputcsv($output, ['Total Properties:', count($data), '', '', '', '', '', '', '', '', '']);
    fputcsv($output, ['Total Portfolio Value:', '₱ ' . number_format($total_value, 2), '', '', '', '', '', '', '', '', '']);
    fputcsv($output, []);
    fputcsv($output, []);
}

// ============================================
// SECTION 2: USERS REPORT
// ============================================
if($report_type == 'users' || $report_type == 'full'){
    fputcsv($output, ['👥 USERS REPORT']);
    fputcsv($output, ['']);
    
    $stmt = $pdo->prepare("
        SELECT id, full_name, email, role, status, phone, address, created_at 
        FROM users 
        WHERE created_at BETWEEN ? AND ?
        ORDER BY created_at DESC
    ");
    $stmt->execute([$date_from, $date_to . ' 23:59:59']);
    $data = $stmt->fetchAll();
    
    fputcsv($output, ['ID', 'Full Name', 'Email', 'Role', 'Status', 'Phone', 'Address', 'Registered Date']);
    
    $admin_count = 0;
    $agent_count = 0;
    $client_count = 0;
    
    foreach($data as $row){
        fputcsv($output, [
            $row['id'],
            $row['full_name'],
            $row['email'],
            strtoupper($row['role']),
            strtoupper($row['status']),
            $row['phone'] ?: '-',
            $row['address'] ?: '-',
            date('Y-m-d', strtotime($row['created_at']))
        ]);
        
        if($row['role'] == 'admin') $admin_count++;
        elseif($row['role'] == 'agent') $agent_count++;
        elseif($row['role'] == 'client') $client_count++;
    }
    
    fputcsv($output, []);
    fputcsv($output, ['SUMMARY', '', '', '', '', '', '', '']);
    fputcsv($output, ['Total Users:', count($data), '', '', '', '', '', '']);
    fputcsv($output, ['Administrators:', $admin_count, '', '', '', '', '', '']);
    fputcsv($output, ['Real Estate Agents:', $agent_count, '', '', '', '', '', '']);
    fputcsv($output, ['Clients:', $client_count, '', '', '', '', '', '']);
    fputcsv($output, []);
    fputcsv($output, []);
}

// ============================================
// SECTION 3: LEADS REPORT
// ============================================
if($report_type == 'leads' || $report_type == 'full'){
    fputcsv($output, ['📋 LEADS MANAGEMENT REPORT']);
    fputcsv($output, ['']);
    
    $stmt = $pdo->prepare("
        SELECT l.id, c.full_name as client, p.title as property, a.full_name as agent, 
               l.stage, l.priority, l.notes, l.created_at
        FROM leads l
        LEFT JOIN users c ON l.client_id = c.id
        LEFT JOIN properties p ON l.property_id = p.id
        LEFT JOIN users a ON l.agent_id = a.id
        WHERE l.created_at BETWEEN ? AND ?
        ORDER BY l.created_at DESC
    ");
    $stmt->execute([$date_from, $date_to . ' 23:59:59']);
    $data = $stmt->fetchAll();
    
    fputcsv($output, ['ID', 'Client Name', 'Property', 'Assigned Agent', 'Stage', 'Priority', 'Notes', 'Date Created']);
    
    $stage_counts = ['new' => 0, 'contacted' => 0, 'viewing' => 0, 'negotiation' => 0, 'closed' => 0];
    
    foreach($data as $row){
        $stage = strtolower($row['stage']);
        if(isset($stage_counts[$stage])) $stage_counts[$stage]++;
        
        fputcsv($output, [
            $row['id'],
            $row['client'] ?: '-',
            $row['property'] ?: '-',
            $row['agent'] ?: 'Unassigned',
            strtoupper($row['stage']),
            strtoupper($row['priority']),
            $row['notes'] ?: '-',
            date('Y-m-d', strtotime($row['created_at']))
        ]);
    }
    
    $total_leads = array_sum($stage_counts);
    $closed = $stage_counts['closed'];
    $conversion = $total_leads > 0 ? round(($closed / $total_leads) * 100, 1) : 0;
    
    fputcsv($output, []);
    fputcsv($output, ['LEAD PIPELINE SUMMARY', '', '', '', '', '', '', '']);
    fputcsv($output, ['Stage', 'Count', '', '', '', '', '', '']);
    fputcsv($output, ['New:', $stage_counts['new'], '', '', '', '', '', '']);
    fputcsv($output, ['Contacted:', $stage_counts['contacted'], '', '', '', '', '', '']);
    fputcsv($output, ['Viewing:', $stage_counts['viewing'], '', '', '', '', '', '']);
    fputcsv($output, ['Negotiation:', $stage_counts['negotiation'], '', '', '', '', '', '']);
    fputcsv($output, ['Closed:', $stage_counts['closed'], '', '', '', '', '', '']);
    fputcsv($output, ['']);
    fputcsv($output, ['Total Leads:', $total_leads, '', '', '', '', '', '']);
    fputcsv($output, ['Closed Deals:', $closed, '', '', '', '', '', '']);
    fputcsv($output, ['Conversion Rate:', $conversion . '%', '', '', '', '', '', '']);
    fputcsv($output, []);
    fputcsv($output, []);
}

// ============================================
// SECTION 4: AGENT PERFORMANCE REPORT
// ============================================
if($report_type == 'agents' || $report_type == 'full'){
    fputcsv($output, ['🏆 AGENT PERFORMANCE REPORT']);
    fputcsv($output, ['']);
    
    $data = $pdo->query("
        SELECT u.id, u.full_name, u.email, u.phone,
               COUNT(DISTINCT l.id) as total_leads,
               SUM(l.stage = 'closed') as closed_deals,
               ROUND(AVG(r.rating), 2) as avg_rating,
               COUNT(DISTINCT r.id) as total_reviews
        FROM users u
        LEFT JOIN leads l ON l.agent_id = u.id
        LEFT JOIN reviews r ON r.agent_id = u.id AND r.is_approved = 1
        WHERE u.role = 'agent'
        GROUP BY u.id
        ORDER BY closed_deals DESC
    ")->fetchAll();
    
    fputcsv($output, ['Rank', 'Agent Name', 'Email', 'Phone', 'Total Leads', 'Closed Deals', 'Conversion Rate', 'Avg Rating', 'Reviews']);
    
    $rank = 1;
    foreach($data as $row){
        $conversion = $row['total_leads'] > 0 ? round(($row['closed_deals'] / $row['total_leads']) * 100, 1) : 0;
        fputcsv($output, [
            $rank++,
            $row['full_name'],
            $row['email'],
            $row['phone'] ?: '-',
            $row['total_leads'] ?: 0,
            $row['closed_deals'] ?: 0,
            $conversion . '%',
            $row['avg_rating'] ? number_format($row['avg_rating'], 1) . ' ★' : 'No ratings',
            $row['total_reviews'] ?: 0
        ]);
    }
    
    fputcsv($output, []);
    fputcsv($output, []);
}

// ============================================
// SECTION 5: REVIEWS & RATINGS REPORT
// ============================================
if($report_type == 'reviews' || $report_type == 'full'){
    fputcsv($output, ['⭐ CLIENT REVIEWS & RATINGS']);
    fputcsv($output, ['']);
    
    $stmt = $pdo->prepare("
        SELECT r.rating, r.comment, r.created_at,
               c.full_name as client_name,
               a.full_name as agent_name,
               p.title as property_title,
               r.is_approved
        FROM reviews r
        JOIN users c ON r.client_id = c.id
        JOIN users a ON r.agent_id = a.id
        LEFT JOIN properties p ON r.property_id = p.id
        WHERE r.created_at BETWEEN ? AND ?
        ORDER BY r.created_at DESC
    ");
    $stmt->execute([$date_from, $date_to . ' 23:59:59']);
    $data = $stmt->fetchAll();
    
    fputcsv($output, ['Client', 'Agent', 'Property', 'Rating', 'Review', 'Status', 'Date']);
    
    $total_rating = 0;
    foreach($data as $row){
        $stars = '';
        for($i = 1; $i <= 5; $i++){
            $stars .= $i <= $row['rating'] ? '★' : '☆';
        }
        
        fputcsv($output, [
            $row['client_name'],
            $row['agent_name'],
            $row['property_title'] ?: '-',
            $stars . ' (' . $row['rating'] . '/5)',
            $row['comment'],
            $row['is_approved'] ? 'Approved' : 'Pending',
            date('Y-m-d', strtotime($row['created_at']))
        ]);
        $total_rating += $row['rating'];
    }
    
    $avg_rating = count($data) > 0 ? round($total_rating / count($data), 1) : 0;
    
    fputcsv($output, []);
    fputcsv($output, ['Average Rating:', $avg_rating . ' / 5.0', '', '', '', '', '']);
    fputcsv($output, ['Total Reviews:', count($data), '', '', '', '', '']);
    fputcsv($output, []);
    fputcsv($output, []);
}

// ============================================
// SECTION 6: FINANCIAL SUMMARY
// ============================================
if($report_type == 'financial' || $report_type == 'full'){
    fputcsv($output, ['💰 FINANCIAL SUMMARY REPORT']);
    fputcsv($output, ['']);
    
    // Property financials
    $total_property_value = $pdo->query("SELECT SUM(price) FROM properties WHERE type='sale'")->fetchColumn() ?: 0;
    $sold_value = $pdo->query("SELECT SUM(price) FROM properties WHERE status='sold'")->fetchColumn() ?: 0;
    $avg_price = $pdo->query("SELECT AVG(price) FROM properties")->fetchColumn() ?: 0;
    $rental_income = $pdo->query("SELECT SUM(price) FROM properties WHERE type='rent'")->fetchColumn() ?: 0;
    
    fputcsv($output, ['PROPERTY FINANCIALS']);
    fputcsv($output, ['Metric', 'Amount (₱)']);
    fputcsv($output, ['Total Portfolio Value', number_format($total_property_value, 2)]);
    fputcsv($output, ['Total Sold Properties Value', number_format($sold_value, 2)]);
    fputcsv($output, ['Average Property Price', number_format($avg_price, 2)]);
    fputcsv($output, ['Projected Monthly Rental Income', number_format($rental_income, 2)]);
    fputcsv($output, []);
    
    // Lead financials
    $closed_leads = $pdo->query("SELECT COUNT(*) FROM leads WHERE stage='closed'")->fetchColumn();
    fputcsv($output, ['LEAD FINANCIALS']);
    fputcsv($output, ['Metric', 'Value']);
    fputcsv($output, ['Total Closed Deals', $closed_leads]);
    fputcsv($output, ['Estimated Commission Revenue (3%)', '₱ ' . number_format($sold_value * 0.03, 2)]);
    fputcsv($output, []);
    fputcsv($output, []);
}

// ============================================
// SECTION 7: MONTHLY TRENDS
// ============================================
if($report_type == 'trends' || $report_type == 'full'){
    fputcsv($output, ['📈 MONTHLY TRENDS REPORT']);
    fputcsv($output, ['']);
    
    // Monthly leads
    $monthly_leads = $pdo->query("
        SELECT DATE_FORMAT(created_at, '%b %Y') as month, 
               COUNT(*) as leads_count,
               SUM(stage = 'closed') as closed_count
        FROM leads
        WHERE created_at >= DATE_SUB(NOW(), INTERVAL 6 MONTH)
        GROUP BY DATE_FORMAT(created_at, '%Y-%m')
        ORDER BY MIN(created_at)
    ")->fetchAll();
    
    fputcsv($output, ['Month', 'Leads Generated', 'Closed Deals', 'Conversion Rate']);
    
    foreach($monthly_leads as $month){
        $conv = $month['leads_count'] > 0 ? round(($month['closed_count'] / $month['leads_count']) * 100, 1) : 0;
        fputcsv($output, [
            $month['month'],
            $month['leads_count'],
            $month['closed_count'],
            $conv . '%'
        ]);
    }
    
    fputcsv($output, []);
    
    // Monthly registrations
    $monthly_users = $pdo->query("
        SELECT DATE_FORMAT(created_at, '%b %Y') as month, 
               COUNT(*) as users_count,
               SUM(role = 'agent') as agents_count,
               SUM(role = 'client') as clients_count
        FROM users
        WHERE created_at >= DATE_SUB(NOW(), INTERVAL 6 MONTH)
        GROUP BY DATE_FORMAT(created_at, '%Y-%m')
        ORDER BY MIN(created_at)
    ")->fetchAll();
    
    fputcsv($output, ['USER REGISTRATION TRENDS']);
    fputcsv($output, ['Month', 'Total Registrations', 'New Agents', 'New Clients']);
    
    foreach($monthly_users as $month){
        fputcsv($output, [
            $month['month'],
            $month['users_count'],
            $month['agents_count'],
            $month['clients_count']
        ]);
    }
    fputcsv($output, []);
    fputcsv($output, []);
}

// ============================================
// SECTION 8: EXECUTIVE SUMMARY
// ============================================
if($report_type == 'full'){
    fputcsv($output, ['📊 EXECUTIVE SUMMARY']);
    fputcsv($output, ['']);
    
    $total_props = $pdo->query("SELECT COUNT(*) FROM properties")->fetchColumn();
    $total_users = $pdo->query("SELECT COUNT(*) FROM users")->fetchColumn();
    $total_leads = $pdo->query("SELECT COUNT(*) FROM leads")->fetchColumn();
    $closed_deals = $pdo->query("SELECT COUNT(*) FROM leads WHERE stage='closed'")->fetchColumn();
    $avg_rating = $pdo->query("SELECT AVG(rating) FROM reviews WHERE is_approved=1")->fetchColumn() ?: 0;
    $pending_reviews = $pdo->query("SELECT COUNT(*) FROM reviews WHERE is_approved=0")->fetchColumn();
    
    fputcsv($output, ['KPI', 'Value', 'Status']);
    fputcsv($output, ['Total Properties', $total_props, '']);
    fputcsv($output, ['Total Users', $total_users, '']);
    fputcsv($output, ['Total Leads', $total_leads, '']);
    fputcsv($output, ['Closed Deals', $closed_deals, '']);
    fputcsv($output, ['Conversion Rate', $total_leads > 0 ? round(($closed_deals / $total_leads) * 100, 1) . '%' : '0%', '']);
    fputcsv($output, ['Average Client Rating', number_format($avg_rating, 1) . ' / 5.0', $avg_rating >= 4 ? 'Excellent' : ($avg_rating >= 3 ? 'Good' : 'Needs Improvement')]);
    fputcsv($output, ['Pending Reviews', $pending_reviews, $pending_reviews > 0 ? 'Action Required' : 'All Reviewed']);
    fputcsv($output, []);
    fputcsv($output, []);
}

// ============================================
// FOOTER
// ============================================
fputcsv($output, ['']);
fputcsv($output, ['============================']);
fputcsv($output, ['END OF REPORT']);
fputcsv($output, ['============================']);
fputcsv($output, []);
fputcsv($output, ['Report generated by Trans-Phil House Hub System']);
fputcsv($output, ['© ' . date('Y') . ' Trans-Phil House Corporation']);
fputcsv($output, ['All rights reserved.']);

fclose($output);
exit;
?>